### ISSUE TITLE
use esp32s3 built-in jtag, what interface should I use

### ISSUE THREAD

**Issue by m986883511** [ThexXTURBOXx/clion-embedded-esp32#11]
![image](https://github.com/ThexXTURBOXx/clion-embedded-esp32/assets/34444109/69e6c452-1064-479f-91ce-d357bc02e849)

usb is:
```shell
ubuntu@ubuntu-vm:~$ lsusb
Bus 003 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 002 Device 002: ID 303a:1001 Espressif USB JTAG/serial debug unit
```

**Comment by ThexXTURBOXx** [comment]
Probably `esp_usb_jtag`, but I am on vacation currently, so I cannot look up the correct one.
The best way to determine this is via trial and error.

Edit: For questions, please don't use GitHub issues, but rather stackoverflow or something similar
