### ISSUE TITLE
Unable to Update Offset

### ISSUE THREAD

**Issue by synologic** [ThexXTURBOXx/clion-embedded-esp32#15]
When trying to edit an existing configuration, the offset is not updatable.

If i change it, the Apply button does not enable and clicking OK does not save the offset value.

It works when creating a new configuration, but not when updating.

**Comment by ThexXTURBOXx** [comment]
Not reproducible on my end (using the version for CLion 2023.3 EAP):

https://github.com/ThexXTURBOXx/clion-embedded-esp32/assets/12763829/d0aedf75-23e3-4f6a-88a7-f1601aaeb5c5

**Comment by synologic** [comment]
Hey Nico,

I meant Offset not Bootloader Offset :)

![image](https://github.com/ThexXTURBOXx/clion-embedded-esp32/assets/10828699/186a6031-db77-4e7f-a896-3fe530ec54d1)

**Comment by ThexXTURBOXx** [comment]
Ah, well, should have checked closer :)
Thanks for reporting back! I have identified and fixed the issue in https://github.com/ThexXTURBOXx/clion-embedded-esp32/commit/83c12816367d0b30653b8f19de313a522fce68af
I have also already uploaded it to the Marketplace. Fix should be published soon!

**Comment by synologic** [comment]
Nico, if it's not too much to ask, 0.3.6 is only available for EAP, can you make it available for the 2023.2 — 2023.2.2 ?
Thanks :)

**Comment by ThexXTURBOXx** [comment]
Sorry, I don't like backporting stuff because it breaks my semantic versioning. I would just suggest waiting a bit until 2023.3 is officially available (which won't take too long, I think - it's already in beta) :)
