### ISSUE TITLE
Trying to create run configuration leads to… no run configuration.

### ISSUE THREAD

**Issue by codingcatgirl** [ThexXTURBOXx/clion-embedded-esp32#16]
## Expected Behavior

I should be able to create a run configuration as explained in the usage guide.

## Actual Behavior

![image](https://github.com/ThexXTURBOXx/clion-embedded-esp32/assets/3868507/e45c7a07-3a7c-4e08-b528-08a350c2ca76)

If i try to create one get a category, but i can't add a run configuration.

Clicking the link on the right to try to create one does nothing. No output if i launch CLion from the console either. 

## Steps to Reproduce the Problem

  1. Install ESP-IDF, create all the configuration
  2. Have the same thing wrong that i have wrong, unfortunately i don't know what. Should this even work on linux?
  3. Try to create a run configuration
  4. Observe no run configuration appearing

## Specifications

  - Plugin Version: 0.3.2
  - CLion version:  2023.2.2
  - OpenOCD version: 0.12.0
  - GDB Version:  12.1
  - STM32CubeMX version: …uh… this is an ESP32-C3, not STM32
  - Toolchain: esp-idf, set up using the environment from the export.sh file set up as a toolchain in CLion
  - Platform: ESP32-C3 / riscv32 / Compiled on Arch Linux
  - Hardware configuration:  AMD64 Laptop compiling for ESP32-C3 riscv32

**Comment by ThexXTURBOXx** [comment]
`CLion version: 2023.3.2` are you sure about that or do you mean `2023.2.3`? :)
I would guess the latter is true, but please correct me if I am mistaken.

Sadly, development has already moved on to `2023.3 EAP`, so you are better off just using that version - it has many more fixes anyway

**Comment by codingcatgirl** [comment]
Oops. Yep, 2023.2.2 is the version I'm using.

 I'll take a look at 2023.3 EAP and see if it also has that issue.

**Comment by codingcatgirl** [comment]
It works with the EAP version, hurray!

On the downside, thanks to that giant feature advertisement in the new version i am now informed about JetBrains jumping onto the LLM hypetrain. What a mess.

Anyway, thanks for your help :)

**Comment by ThexXTURBOXx** [comment]
Thanks for the quick feedback! Glad it works in EAP!

And well, I'll just let them have their fun until it's no longer fun :)
