### ISSUE TITLE
Upgrade Gradle Plugin version

### ISSUE THREAD

**Issue by jeongyeham** [ThexXTURBOXx/clion-embedded-esp32#20]
Hi Nico，
## WHY?
I have noticed the update regarding your version, where the IDE has been upgraded to version 242*.
It seems that version 242 requires a higher version of the Gradle plugin.
Please checkout this [link](https://plugins.jetbrains.com/docs/intellij/build-number-ranges.html#platformVersions)

**Comment by ThexXTURBOXx** [comment]
I have also received an email regarding this the other day. Will upgrade it in the next update for the plugin!

**Comment by ThexXTURBOXx** [comment]
Done in 0.4.0! :)

**Comment by jeongyeham** [comment]
Thanks for your work!
